# Generated by Django 3.1.1 on 2020-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
