# Generated by Django 3.1.1 on 2020-10-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_article_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
